### ISSUE TITLE
`getPort()` return the default `http` port, not the one from the URL

### ISSUE THREAD

**Issue by spouliot** [lbussy/LCBUrl#13]
### Basic Infos

- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:				ESP32
- Core Version:			not sure
- Development Env:		PlatformIO
- Operating System:		macOS

### Settings in IDE

- Module:			Espressif 32 (2.1.0) > Espressif ESP32 Dev Module
- Flash Mode:			?
- Flash Size:			4MB
- lwip Variant:		?
- Reset Method:		RTS
- Flash Frequency:	?
- CPU Frequency:	240MHz
- Upload Using:		SERIAL
- Upload Speed:		115200

### Problem Description

It seems `getPort()` return the scheme's default instead of the port provided in the URL.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {
  LCBUrl parser;
  if (parser.setUrl ("http://192.168.2.16:5000/")) {
    Serial.printf ("Host: %s\n", parser.getHost().c_str());
    Serial.printf ("Port: %d\n", parser.getPort());
  }
  delay (5000);
}

```

### Debug Messages

```
Host: 192.168.2.16
Port: 80
...
```

**Comment by lbussy** [comment]
Well that's not right, is it?  :)  I'll have a look.

**Comment by spouliot** [comment]
`getRawAuthority` returns `192.168.2.16:5000`
so `endloc` will be `-1` and `port` won't be assigned

```diff
-            if ((startloc != -1) && (endloc != -1))
+            if (startloc != -1)
```
^ that fix the issue for me.

That might have regressed when you removed the last `/` ?

**Comment by lbussy** [comment]
In devel, ready to be tested.
