### ISSUE TITLE
New ESP32 Framework Kills IPAddress Check

### ISSUE THREAD

**Issue by lbussy** [lbussy/LCBUrl#21]
Using an updated [arduino-esp32](https://github.com/espressif/arduino-esp32) build the folowing errors were raised:

```
.pio\libdeps\tft_espi\LCBUrl\src\LCBUrl.cpp:301:23: error: ambiguous overload for 'operator==' (operand types are 'IPAddress' and 'u32_t {aka unsigned int}')
         if (ipaddress == IPADDR_NONE)
```

Apparently `IPADDR_NONE` is now a `u32_t`.

**Comment by magillus** [comment]
@lbussy thank for showing work around, will this be released in new version? (I use PlatformIO)

**Comment by lbussy** [comment]
It is in the devel branch right now, it will be released as soon as I can here.  I was hoping to get a few more tests done.
