### ISSUE TITLE
PlatformIO 1.1.3 version doesn't reflect tag 1.1.3

### ISSUE THREAD

**Issue by magillus** [lbussy/LCBUrl#25]
Hello I noticed that recent release with https://github.com/lbussy/LCBUrl/releases/tag/1.1.3 is not available on PlatformIO - https://libraries.io/platformio/LCBUrl (see latest release date)

Both have same version number but not same code.

Can you have 1.1.4 version that works on PlatformIO? 

Thank you for great library
Mateusz

**Comment by magillus** [comment]
Also when using master directly in PlatformIO this line throws errors:
https://github.com/lbussy/LCBUrl/blob/master/src/LCBUrl.h#L47
after commenting it out - it worked fine with direct master import.

**Comment by lbussy** [comment]
Ah, crap - forgot to remove that debug line!

I'll try to get both of these fixed today.

**Comment by lbussy** [comment]
The library managers (Arduino and PlatformIO) lag a bit.  They should catch up within a day or so.

**Comment by magillus** [comment]
Thank you very much, github master build is good enough until fully deployed.
