### ISSUE TITLE
getAfterPath() was changed from public to private

### ISSUE THREAD

**Issue by thorrak** [lbussy/LCBUrl#42]
Commit https://github.com/lbussy/LCBUrl/commit/0c86cc7cbc9d1901648a0d485da38afa0590cc18 changed getAfterPath() from being public to [private](https://github.com/lbussy/LCBUrl/blob/ddbbc79fe73b038cc89eea2c672977ade64b41e8/src/LCBUrl.h#L101). This was a breaking change, as getAfterPath is used in [TiltBridge](https://github.com/thorrak/tiltbridge/blob/81b780aa4dae4786a31775c3ee93221e2692a15d/src/sendData.cpp#L624). 

This is actually quite helpful when manually constructing HTTP requests, and thus would be helpful to be public.

**Comment by thorrak** [comment]
This is fixed by #43

**Comment by lbussy** [comment]
You should have read my mind.

**Comment by lbussy** [comment]
Okay I've compromised:  I've marked this as deprecated but left it as public.  In the future you should be able to concatenate what you need from the RFC 3986 components.

**Comment by thorrak** [comment]
Here's what I ended up replacing getAfterPath with:

```
String lcburl_getAfterPath(LCBUrl url) // Get anything after the path
{
    String afterpath = "";

    if (url.getQuery().length() > 0) {
        afterpath = "?" + url.getQuery();
    }

    if (url.getFragment().length() > 0) {
        afterpath = afterpath + "#" + url.getFragment();
    }

    return afterpath;
}
```

Not sure entirely how I feel about the above, given all the String mutation, but it solves the problem while using non-deprecated interfaces.

**Comment by lbussy** [comment]
It's not efficient - I'm all ears how to get some more efficiencies out of the library.

**Comment by thorrak** [comment]
make getAfterPath public. :)

**Comment by lbussy** [comment]
It is!   Says right there, `public`.

**Comment by lbussy** [comment]
You talked me into it - 1.1.8 will have this reverted.
